config/routes.rb
LastFMVkontakte::Application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    root to: 'page#home'

    match '/terms', to: 'page#terms'
    match '/privacy', to: 'page#privacy'
    match '/about', to: 'page#about'

    match '/app', to: 'app#home'
    get 'app/connect'
    get 'app/settings'
  end

end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
  end

  def connect
  end

  def settings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || extract_locale_from_accept_language_header || I18n.default_locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

  private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def terms
  end

  def privacy
  end

  def about
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/app/connect.html.erb
<h1>App#connect</h1>
<p>Find me in app/views/app/connect.html.erb</p>

app/views/app/home.html.erb
<h1>App#home</h1>
<p>Find me in app/views/app/home.html.erb</p>

app/views/app/settings.html.erb
<h1>App#settings</h1>
<p>Find me in app/views/app/settings.html.erb</p>

app/views/layouts/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only"><%=t :toggle_navigation %></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'LastVK', root_path, class: 'navbar-brand' %>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
      <%= active_link_to t(:home),    root_path,    :wrap_tag => :li, :active => :exclusive %>
      <%= active_link_to t(:about),   about_path,   :wrap_tag => :li %>
      <%= active_link_to t(:terms),   terms_path,   :wrap_tag => :li %>
      <%= active_link_to t(:privacy), privacy_path, :wrap_tag => :li %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="javascript:void('<%=t :dota_easter_egg %>')" class="dropdown-toggle" data-toggle="dropdown"><%=t :language %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to t(:russian), '' %>
            <%= link_to t(:english), '' %>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="javascript:void('<%=t :dota_easter_egg %>')" class="dropdown-toggle" data-toggle="dropdown"><%=t :sign_in %> <b class="caret"></b></a>
        <ul class="dropdown-menu login-menu">
          <li>
            <button class="btn btn-vk btn-with-icon btn-block">
              <%= fa_icon 'vk', text: t(:sign_in_with_VK) %>
            </button>
            <button class="btn btn-danger btn-with-icon btn-block">
              <%= fa_icon 'key', text: t(:sign_in_with_LastFM) %>
            </button>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>

app/views/layouts/_navbar_app.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only"><%=t :toggle_navigation %></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'LastVK', app_path, class: 'navbar-brand' %>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
      <%= active_link_to t(:home), app_path, :wrap_tag => :li, :active => :exclusive %>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Yurijmi">

  <title><%=t :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "app" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<%= render 'layouts/navbar_app' %>

<div class="container">
  <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%=t :description %>">
  <meta name="author" content="Yurijmi">
  <link rel="shortcut icon" href="<%= "//#{request.host}:#{request.port}/favicon.ico" %>">

  <title><%=t :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <%= yield %>
</div> <!-- /container -->

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/home.html.erb
<div class="jumbotron">
  <h1><%=t :welcome_heading %></h1>
  <p><%=t :welcome_text %></p>
  <%= link_to fa_icon('info', text: t(:about)), about_path,
              class: 'btn btn-primary btn-with-icon btn-lg',
              role: 'button' %>
  <%= link_to fa_icon('play', text: t(:launch)), 'https://vk.com/app4051735',
              class: 'btn btn-success btn-with-icon btn-lg',
              role: 'button',
              target: '_blank' %>
</div>

app/views/page/terms.en.html.erb
<h1 class="mar-bot"><%=t :terms %></h1>

<article>

  <h3>1. Basic Terms</h3>

  <section>

    <p>
      <b>Site</b> — site in the Internet at <a href="http://vk.com/" rel="nofollow" target="_blank">http://vk.com/</a>.
    </p>

    <p>
      <b>Developer</b> — individual or legal entity that places an Application on the Site and uses it according to the Terms for Application Placement and Rules for Application Placement on the Site. Name, last name and patronymic or company name of the Developer and other related information are specified in "About Developer" section in the Application start window and also in Application settings.
    </p>

    <p>
      <b>Site Administration</b> — V Kontakte limited liability company located at: Lit. B, 8, Tverskaya st., Saint Petersburg, 191015
    </p>

    <p>
      <b>Application</b> — software service placed by the Developer on the Site in "Applications" section, which had been moderated by the Site Administration and included into the application catalog.
    </p>

    <p>
      <b>User</b> — duly registered Site user who utilizes the Application.
    </p>

  </section>

  <h3>2. Status of the Rules</h3>

  <section>

    <p>
      <b>2.1.</b> These Rules are an agreement between the Developer and User (collectively referred to as "Parties") and regulate rights and obligations of the Developer and User concerning Application use.
    </p>

    <p>
      <b>2.2.</b> These Rules are an official standard document of Developers. These Rules shall be applied to such relations in case the Developer has not approved and does not use its own Service Rules, and the link to such Rules shall be published for Users in the Application start window and also in Application settings.
    </p>

    <p>
      <b>2.3.</b> Existing revision of the Rules which is a public document has been developed by the Site Administration and is available for all users in the Internet when they click "Service Rules for Application Developer" hyperlink.
      <div class="pull-me">
        <p>
          Site Administration has the right to amend the Rules. When amending the Rules, the Site Administration notifies users by publishing a new revision of the Rules on the Site at the permanent address of <%= link_to "http://#{request.host}"+terms_path+'/', terms_path %> not later than 10 days prior to coming into effect of such amendments. Previous revisions of the Rules are stored in the document archive of the Site Administration.
        </p>
        <p>
          <b>2.3.</b> Provisions of these Rules are a public offer according to Article 437 of the Civil Code of the Russian Federation. The User shall read the Rules in full prior to first start of the Application. When User starts the Application he/she unambiguously accepts these Rules according to Article 438 of the Civil Code of the Russian Federation. Provisions of the Rules can be accepted only in full, with no exceptions.
        </p>
      </div>
    </p>

    <p>
      <b>2.4.</b> After Application start, Users can find the link to these Rules on "About Developer" tab. The User shall check the current version of the Rules in Application settings ever and again in order to be aware of amendments and/or supplements. When User continues to use the Application after such amendments of the Rules have been made, the User accepts and agrees with such amendments and/or supplements.
    </p>

  </section>

  <h3>3. Parties' Rights and Responsibilities</h3>

  <section>

    <p>
      <b>3.1.</b> The User shall read information about the Developer, Developer's confidentiality policy and these Rules prior to first start of the Application. In case the User does not agree with provisions of such documents, the User shall not start and use the Application.
    </p>

    <p>
      <b>3.2.</b> User shall use the Application for personal non-commercial purposes. Services related to Application use shall not be offered to other Users in order to gain profit. Automated scripts (bots) and other means of interaction with the Application without the User are prohibited. Actions to prevent normal operation of the Application and special programs with malicious components (viruses) are prohibited.
    </p>

    <p>
      <b>3.3.</b> The Developer has the right to change Application functionality, its interface and/or content with or without User notification at any time.
    </p>

    <p>
      <b>3.4.</b> The Developer, in its sole discretion, reserves the right to set the cost of individual services the Application offers, in Application internal currency — votes. The User shall use methods of adding User's personal account in the Application and further operate with votes with good faith. In case the Developer detects unauthorized adding to User's personal account in the Application, the Developer has the right to cancel further services for the User or to debit User's personal account in the Application in its sole discretion.
    </p>

    <p>
      <b>3.5.</b> The Developer has the right to request and use information about the User solely for the purposes of Application service provision. Use of information about the User shall be governed by the Developer's confidentiality policy.
    </p>

    <p>
      <b>3.6.</b> The Developer shall provide technical support for the Application and simple communication procedure with Users regarding all issues that may occur during Application use — in "Help" section and in Application settings, on "About Developer" tab.
    </p>

  </section>

  <h3>4. Intellectual Property</h3>

  <section>

    <p>
      <b>4.1.</b> The User agrees that the Application, its interface and content (including but not limited to design elements, text, graphics, images, video, scripts, programs, music, audios and other objects and their compilations related to the Application) are protected with copyright, trademarks, patents and other rights belonging to the Developer or other legitimate rightholders.
    </p>

    <p>
      <b>4.2.</b> The Developer shall provide the User with a non-exclusive license to use the Application: namely, start and further use of the Application only to meet personal, family, home or other non-commercial needs, without the right to transfer the license to third parties and without the right to provide sublicenses for third parties to use the Application.
    </p>

    <p>
      <b>4.3.</b> The User shall not copy, change, delete, rework (including any translation or localization), sell, lease, publish, download or otherwise distribute the Application or its components, decompile or otherwise extract the source code of Application components that are the software, and also change Application functionality without prior written consent of the Developer.
    </p>

    <p>
      <b>4.4.</b> The User shall not delete and/or change any information the Developer has published in the Application, including copyright and personalization symbols.
    </p>

    <p>
      <b>4.5.</b> License specified in Item 4.2 of these Rules shall be provided for the whole period when the User utilizes the Application. This license also covers all updates and/or additional components of the Application that the Developer can provide later.
    </p>

    <p>
      <b>4.6.</b> Unless otherwise stated in the Rules, nothing in the Rules cannot be considered as transfer of exclusive rights for the Application and/or its components to the User.
    </p>

  </section>

  <h3>5. Guarantees and Responsibility</h3>

  <section>

    <p>
      <b>5.1.</b> The User accepts and agrees that the Application is provided "as is." The Developer grants no guarantee regarding consequences of Application use, Application interaction with other software.
    </p>

    <p>
      <b>5.2.</b> The Developer does not guarantee that the Application will suit for specific purposes. The User accepts and agrees that the result of Application use may not meet User's expectations.
    </p>

    <p>
      <b>5.3.</b> The Developer or other rightholders, under no circumstances, shall not be responsible for any indirect, accidental damage (including loss of profit, damaged caused by data loss) suffered due to Application use or inability to use, including Application failure or any other interruption in Application use even if the Developer has warned about or mentioned possibility of such damage.
    </p>

    <p>
      <b>5.4.</b> The User bears own responsibility for how he/she uses the Application, including publication and transfer of information, comments, images and other materials to other Users by means of the Application. The User bears own responsibility for observation of third party rights, applicable laws, these Rules, Developer's rules and/or mandatory instructions published in "Help" section of the Application, when using the Application.
    </p>

    <p>
      <b>5.5.</b> If User infringes, the Developer has the right to cancel further services for the User or fully or partially limit such services with or without User notification.
    </p>

  </section>

  <h3>6. Final Provisions</h3>

  <section>

    <p>
      <b>6.1.</b> The User has the right to discontinue the use of services at any time by removing the Application from his/her personal page on the Site.
    </p>

    <p>
      <b>6.2.</b> The Developer has the right to suspend or stop Application operation at any time with or without User notification.
    </p>

    <p>
      <b>6.3.</b> These Rules are governed and interpreted according to the legislation of the Russian Federation. Issues not covered by the Rules shall be settled according to the legislation of the Russian Federation.
    </p>

    <p>
      <b>6.4.</b> In case of any dispute or difference related to observance of these Rules, the Developer and User shall endeavor best efforts to settle them by means of negotiations therebetween. In case disputes cannot be resolved through negotiations, such disputes shall be settled according to the procedure established by the existing legislation of the Russian Federation.
    </p>

    <p>
      <b>6.5.</b> These Rules have been written in the Russian language and can be provided for review in other language. In case the Russian version of the Rules and version of the Rules in other language differ, provisions of the Russian version of the Rules shall apply.
    </p>

    <p>
      <b>6.6.</b> If, for one reason or another, one or more provisions of these Rules are invalidated, this shall not affect validity and applicability of other provisions.
    </p>

  </section>

</article>

app/views/page/terms.ru.html.erb
<h1 class="mar-bot"><%=t :terms %></h1>

<article>

  <h3>1. Основные понятия</h3>

  <section>

    <p>
      <b>Сайт</b> – сайт, расположенный в сети Интернет по адресу <a href="http://vk.com/" rel="nofollow" target="_blank">http://vk.com/</a>.
    </p>

    <p>
      <b>Разработчик</b> – физическое или юридическое лицо, размещающее приложение на Сайте и использующее его в соответствии с Условиями размещения приложений и Правилами размещения приложений на Сайте. Фамилия, имя и отчество либо наименование Разработчика, а также иная информация о нем указаны в разделе &laquo;Информация о разработчике&raquo; в окне запуска Приложения и в настройках Приложения.
    </p>

    <p>
      <b>Администрация Сайта</b> – общество с ограниченной ответственностью &laquo;В Контакте&raquo;, расположенное по адресу: 191015, Санкт-Петербург, ул. Тверская, д. 8, лит. Б.
    </p>

    <p>
      <b>Приложение</b> – программный сервис, размещенный Разработчиком на Сайте в разделе &laquo;Приложения&raquo;, прошедший модерацию Администрацией Сайта и включенный в каталог приложений.
    </p>

    <p>
      <b>Пользователь</b> – пользователь Сайта, зарегистрированный в установленном порядке и использующий Приложение.
    </p>

  </section>

  <h3>2. Статус Правил</h3>

  <section>
    <p>
      <b>2.1.</b> Настоящие Правила представляют собой соглашение между Разработчиком и Пользователем (далее вместе именуемые &laquo;Стороны&raquo;) и регулируют права и обязанности Разработчика и Пользователя в связи с использованием Приложения.
    </p>

    <p>
      <b>2.2.</b> Настоящие Правила являются официальным типовым документом Разработчиков. Настоящие Правила применяются к указанным отношениям в случае, если Разработчик не утвердил и не применяет свои собственные Правила оказания услуг, ссылка на которые предоставляется Пользователям в окне запуска Приложения и в настройках Приложения.
    </p>

    <p>
      <b>2.3.</b> Действующая редакция Правил, являющихся публичным документом, разработана Администрацией Сайта и доступна любому пользователю сети Интернет при переходе по гипертекстовой ссылке &laquo;Правила оказания услуг разработчика приложения&raquo;.
      <div class="pull-me">
        <p>
          Администрация Сайта вправе вносить изменения в настоящие Правила. При внесении изменений в Правила Администрация Сайта уведомляет об этом пользователей путем размещения новой редакции Правил на Сайте по постоянному адресу <%= link_to "http://#{request.host}"+terms_path+'/', terms_path %> не позднее, чем за [10] дней до вступления в силу соответствующих изменений. Предыдущие редакции Правил хранятся в архиве документации Администрации Сайта.
        </p>
        <p>
          <b>2.3.</b> Положения настоящих Правил рассматриваются как публичная оферта в соответствии со ст. 437 Гражданского кодекса Российской Федерации. Пользователь обязан полностью ознакомиться с настоящими Правилами до первого запуска Приложения. Запуск Приложения Пользователем означает полное и безоговорочное принятие Пользователем настоящих Правил в соответствии со ст. 438 Гражданского кодекса Российской Федерации. Положения настоящих Правил могут быть приняты только в целом без каких-либо изъятий.
        </p>
      </div>
    </p>

    <p>
      <b>2.4.</b> Ссылка на настоящие Правила после запуска Приложения доступна в настройках Приложения, во вкладке &laquo;Информация о разработчике&raquo;. Пользователь обязан время от времени проверять текущую версию настоящих Правил в настройках Приложения на предмет внесения изменений и/или дополнений. Продолжение использования Приложения Пользователем после вступления в силу соответствующих изменений настоящих Правил означает принятие и согласие Пользователя с такими изменениями и/или дополнениями.
    </p>

  </section>

  <h3>3. Права и обязанности Сторон</h3>

  <section>

    <p>
      <b>3.1.</b> Пользователь обязан ознакомиться с информацией о Разработчике, политикой конфиденциальности Разработчика и настоящими Правилами до первого запуска Приложения. При несогласии с положениями указанных документов Пользователь обязан воздержаться от запуска и использования Приложения.
    </p>

    <p>
      <b>3.2.</b> Пользователь обязуется использовать Приложение в личных некоммерческих целях. Запрещается предлагать услуги, связанные с использованием Приложения, другим Пользователям в целях извлечения прибыли. Запрещается использование каких-либо автоматических скриптов (&laquo;программы-роботы&raquo;) или иных средств, позволяющих взаимодействовать с Приложением без участия Пользователя. Запрещается совершать действия, направленные на нарушение нормального функционирования Приложения, и использовать специальные программы, содержащие вредоносные компоненты (&laquo;вирусы&raquo;).
    </p>

    <p>
      <b>3.3.</b> Разработчик вправе в любое время вносить изменения в функционал Приложения, интерфейс и/или содержание Приложения с уведомлением Пользователей или без такового.
    </p>

    <p>
      <b>3.4.</b> Разработчик вправе в одностороннем порядке устанавливать стоимость отдельных сервисов, предлагаемых Приложением, выраженную во внутренней валюте Приложений - голосах. Пользователь обязуется добросовестно использовать способы пополнения личного счета Пользователя в Приложении и дальнейшего использования голосов. При обнаружении Разработчиком фактов неправомерного пополнения личного счета Пользователя в Приложении Разработчик вправе отказать Пользователю в дальнейшем предоставлении услуг либо в одностороннем порядке уменьшить личный счет Пользователя в Приложении.
    </p>

    <p>
      <b>3.5.</b> Разработчик вправе запросить и использовать информацию о Пользователе исключительно в целях предоставления услуг по использованию Приложения. Использование информации о Пользователе регулируется политикой конфиденциальности Разработчика.
    </p>

    <p>
      <b>3.6.</b> Разработчик обязан обеспечить техническую поддержку Приложения и предоставить простой способ связи для обращений Пользователей по всем возникающим в процессе использования Приложения вопросам в разделе &laquo;Помощь&raquo; и в настройках Приложения, во вкладке &laquo;Информация о разработчике&raquo;.
    </p>

  </section>

  <h3>4. Интеллектуальная собственность</h3>

  <section>

    <p>
      <b>4.1.</b> Пользователь признает, что Приложение, его интерфейс и содержание (включая, но не ограничиваясь, элементы дизайна, текст, графические изображения, иллюстрации, видео, скрипты, программы, музыка, звуки и другие объекты и их подборки, связанные с Приложением) защищены авторским правом, товарными знаками, патентами и иными правами, которые принадлежат Разработчику или иным законным правообладателям.
    </p>

    <p>
      <b>4.2.</b> Разработчик предоставляет Пользователю неисключительную лицензию на использование Приложения, а именно на запуск и дальнейшую эксплуатацию Приложения исключительно в целях удовлетворения личных, семейных, домашних или иных не связанных с предпринимательской деятельностью нужд, без права передачи данной лицензии третьим лицам и без права предоставления сублицензий на использование Приложения третьим лицам.
    </p>

    <p>
      <b>4.3.</b> Пользователь не вправе воспроизводить, копировать, изменять, уничтожать, перерабатывать (включая выполнение любого перевода или локализации), продавать, сдавать в прокат, опубликовывать, скачивать, иным образом распространять Приложение либо его компоненты, декомпилировать или иным образом пытаться извлечь исходный код компонентов Приложения, являющихся программным обеспечением, а также изменять функционал Приложения без предварительного письменного согласия Разработчика.
    </p>

    <p>
      <b>4.4.</b> Пользователь не вправе удалять и/или изменять какую-либо информацию, размещенную Разработчиком в рамках Приложения, в том числе знаки охраны авторского права и средств индивидуализации.
    </p>

    <p>
      <b>4.5.</b> Лицензия, указанная в пункте 4.2 настоящих Правил, предоставляется на весь срок использования Приложения Пользователем. Данная лицензия распространяется также на все обновления и/или дополнительные компоненты Приложения, которые могут быть созданы и предоставлены Разработчиком в будущем.
    </p>

    <p>
      <b>4.6.</b> Если иное явным образом не установлено в настоящих Правилах, ничто в настоящих Правилах не может быть рассмотрено как передача исключительных прав на Приложение и/или его компоненты Пользователю.
    </p>

  </section>

  <h3>5. Гарантии и Ответственность</h3>

  <section>

    <p>
      <b>5.1.</b> Пользователь признает и соглашается с тем, что Приложение предоставляется на условиях &laquo;как есть&raquo;. Разработчик не предоставляет гарантий в отношении последствий использования Приложения, взаимодействия Приложения с другим программным обеспечением.
    </p>

    <p>
      <b>5.2.</b> Разработчик не предоставляет гарантий того, что Приложение может подходить для конкретных целей использования. Пользователь признает и соглашается с тем, что результат использования Приложения может не соответствовать ожиданиям Пользователя.
    </p>

    <p>
      <b>5.3.</b> Разработчик или иные правообладатели ни при каких обстоятельствах не несут ответственность за любой косвенный, случайный, неумышленный ущерб (включая упущенную выгоду, ущерб, причиненный утратой данных), вызванный в связи с использованием Приложения или невозможностью его использования, в том числе в случае отказа работы Приложения или иного перерыва в использовании Приложения, даже если Разработчик предупреждал или указывал на возможность такого ущерба.
    </p>

    <p>
      <b>5.4.</b> Пользователь самостоятельно несет ответственность за свои действия по использованию Приложения, в том числе за действия по размещению и передаче информации, комментариев, изображений и иных материалов другим Пользователям с помощью Приложения. Пользователь самостоятельно несет ответственность за соблюдение прав третьих лиц, применимого законодательства, настоящих Правил, каких-либо правил и/или обязательных инструкций Разработчика, размещенных в разделе &laquo;Помощь&raquo; Приложения, при использовании Приложения.
    </p>

    <p>
      <b>5.5.</b> За нарушения, допущенные Пользователем, Разработчик вправе отказать Пользователю в дальнейшем предоставлении услуг или ограничить такое предоставление полностью или частично с уведомлением Пользователя или без такового.
    </p>

  </section>

  <h3>6. Заключительные положения</h3>

  <section>
    <p>
      <b>6.1.</b> Пользователь вправе в любой момент отказаться от предоставления услуг посредством удаления Приложения со своей персональной страницы на Сайте.
    </p>

    <p>
      <b>6.2.</b> Разработчик вправе в любой момент приостанавливать или прекращать функционирование Приложения с уведомлением Пользователей или без такового.
    </p>

    <p>
      <b>6.3.</b> Настоящие Правила регулируются и толкуются в соответствии с законодательством Российской Федерации. Вопросы, не урегулированные Правилами, подлежат разрешению в соответствии с законодательством Российской Федерации.
    </p>

    <p>
      <b>6.4.</b> В случае возникновения любых споров или разногласий, связанных с исполнением настоящих Правил, Разработчик и Пользователь приложат все усилия для их разрешения путем проведения переговоров между ними. В случае, если споры не будут разрешены путем переговоров, споры подлежат разрешению в порядке, установленном действующим законодательством Российской Федерации.
    </p>

    <p>
      <b>6.5.</b> Настоящие Правила составлены на русском языке и могут быть предоставлены Пользователю для ознакомления на другом языке. В случае расхождения русскоязычной версии Правил и версии Правил на ином языке, применяются положения русскоязычной версии настоящих Правил.
    </p>

    <p>
      <b>6.6.</b> Если по тем или иным причинам одно или несколько положений настоящих Правил будут признаны недействительными или не имеющими юридической силы, это не оказывает влияния на действительность или применимость остальных положений.
    </p>

  </section>

</article>